import React from 'react';

const companies = [
  {name:'Johnson & Johnson', types:['Licensing','Strategic collaboration','Acquisition','Venture investment'], focus:'Works across early-stage innovation through later-stage licensing and acquisition; J&J Innovation also includes venture investment through JJDC.', url:'https://www.jnj.com/innovativemedicine/partnerships'},
  {name:'Pfizer', types:['Licensing','Acquisition','Research collaboration','Venture / seed investment'], focus:'Publicly describes partnership models including licensing, acquisitions, research collaborations, venture investments, academic alliances, early-stage seed funding and incubators.', url:'https://www.pfizer.com/about/partners/research-and-business-development-partnerships/'},
  {name:'Novartis', types:['In-licensing','Out-licensing','Risk sharing','Research collaboration','Options','Equity investment','Acquisition'], focus:'Uses flexible deal structures across stages and publicly identifies licensing, risk-sharing, research collaborations, options, equity investments and acquisitions among its partnering models.', url:'https://www.novartis.com/partnering'},
  {name:'Roche', types:['Licensing','Development collaboration','Acquisition','Diagnostics partnership'], focus:'Maintains a large global partnering network across Pharma and Diagnostics and publicly describes licensing, development collaborations and acquisitions as routes for external innovation.', url:'https://www.roche.com/innovation/partnering'}
];

export default function DealCompanies(){return <div className="investor-panel"><span className="eyebrow">Potential deal counterparties</span><h2>Companies that actively use multiple partnering structures</h2><p>These companies publicly maintain business-development or partnering programs and use several transaction structures. Inclusion is a research starting point—not a statement that a company is currently interested in your specific asset or that it will transact on particular terms.</p><div className="funding-list">{companies.map(company=><article key={company.name}><h3>{company.name}</h3><div className="talk-list">{company.types.map(type=><span key={type}>{type}</span>)}</div><p>{company.focus}</p><a href={company.url} target="_blank" rel="noreferrer">Review official partnering information →</a></article>)}</div><p className="small">Before outreach, compare the company’s current therapeutic or technology focus, development-stage interests, geographic priorities, transaction size, and submission requirements with your program.</p></div>}
