const ownershipOptions=[['The company / organization owns it directly','company-owned'],['Founder(s) or individual inventor(s) currently own it','founder-owned'],['University / research institution owns or controls it','university-owned'],['Licensed from a university or other third party','licensed-in'],['Jointly owned with another company, institution, or collaborator','jointly-owned'],['Ownership is unclear or still being documented','ownership-unclear'],['Other ownership arrangement','ownership-other']];
const ownershipLegalNotes={
'company-owned':'Confirm that all founders, employees, consultants, contractors, and collaborators have executed appropriate invention-assignment documents and that the entity actually holds the relevant patent, software, data, know-how, and other IP rights.',
'founder-owned':'Consider whether the relevant IP should be assigned or licensed to the operating company before financing or partnering. Investors and counterparties commonly diligence chain of title and the company’s authority to grant rights.',
'university-owned':'Review the institution’s technology-transfer policies and any sponsored-research, government-funding, inventor, publication, or third-party obligations before assuming the company can commercialize or sublicense the technology.',
'licensed-in':'Review the underlying license for field, territory, exclusivity, sublicensing, diligence, payment, assignment, change-of-control, patent, improvement, regulatory-data, and termination provisions before negotiating downstream rights.',
'jointly-owned':'Joint ownership can create significant commercialization and enforcement issues. Review the governing collaboration documents and applicable law to determine each owner’s ability to use, license, enforce, assign, or transfer its interest.',
'ownership-unclear':'Resolve chain-of-title questions early. Identify inventors and contributors, employment and consulting relationships, institutional policies, funding sources, prior agreements, and any assignments or licenses affecting the technology.',
'ownership-other':'Document the ownership structure and identify every person or entity whose consent, assignment, license, waiver, or approval may be required for development, financing, licensing, or a sale of the technology.'};
let ownershipGateShown=false;
function isStatePage(){return [...document.querySelectorAll('#root h1')].some(h=>h.textContent.trim()==='Which state are you operating in?');}
function buildOwnershipPage(stateScreen){
 const page=document.createElement('section');page.dataset.ownershipQuestion='true';page.className='question-screen ownership-standalone-page';
 page.innerHTML=`<div class="question ownership-page-inner"><span class="eyebrow">Legal decision · Ownership & chain of title</span><h1>Who owns the technology?</h1><p class="ownership-lead">Identify who currently owns or controls the intellectual property that will be developed, financed, licensed, or commercialized. Chain of title can determine whether the organization has authority to grant rights, raise financing, enter a strategic transaction, or sell the asset.</p><div class="ownership-callout"><strong>Why this matters legally</strong><p>Before a financing, license, collaboration, or acquisition, counterparties commonly diligence ownership of patents, patent applications, software, data, know-how, inventions, regulatory materials, and other technology rights, together with any third-party restrictions.</p></div><div class="ownership-options">${ownershipOptions.map(([label,value])=>`<button type="button" class="ownership-option" data-value="${value}">${label}</button>`).join('')}</div><div class="ownership-other-wrap" hidden><label><strong>Please describe the ownership arrangement</strong><input type="text" class="ownership-other-input" placeholder="e.g., owned through a joint venture or subject to an option agreement"/></label></div><div class="ownership-legal-note" hidden></div><div class="ownership-checklist"><h2>Ownership issues to diligence</h2><div class="ownership-check-grid"><div><strong>Chain of title</strong><span>Founder, employee, consultant, contractor, inventor and collaborator assignments.</span></div><div><strong>Third-party rights</strong><span>Existing licenses, options, liens, security interests, ROFR/ROFN rights and required consents.</span></div><div><strong>Institutional obligations</strong><span>University policies, sponsored research, grant terms and government-funding obligations.</span></div><div><strong>Scope of ownership</strong><span>Patents, software, know-how, data, improvements, materials and regulatory documentation.</span></div><div><strong>Transaction authority</strong><span>Whether the company can license, sublicense, assign, encumber or sell the relevant rights.</span></div><div><strong>Future development</strong><span>Who will own improvements, new inventions, jointly developed IP and resulting data.</span></div></div></div><div class="nav-row"><button type="button" class="primary ownership-continue" disabled>Continue to state →</button></div><p class="ownership-disclaimer">This page is designed for legal issue spotting. Ownership and licensing consequences depend on the governing agreements and applicable law.</p></div>`;
 stateScreen.style.display='none';stateScreen.insertAdjacentElement('beforebegin',page);
 const saved=sessionStorage.getItem('healthtech-ownership')||'',savedOther=sessionStorage.getItem('healthtech-ownership-other')||'',note=page.querySelector('.ownership-legal-note'),otherWrap=page.querySelector('.ownership-other-wrap'),otherInput=page.querySelector('.ownership-other-input'),continueBtn=page.querySelector('.ownership-continue');otherInput.value=savedOther;
 function select(value){sessionStorage.setItem('healthtech-ownership',value);page.querySelectorAll('.ownership-option').forEach(b=>b.classList.toggle('selected',b.dataset.value===value));otherWrap.hidden=value!=='ownership-other';note.hidden=false;note.innerHTML=`<strong>Legal consideration:</strong> ${ownershipLegalNotes[value]||''}`;continueBtn.disabled=value==='ownership-other'&&!otherInput.value.trim();}
 page.querySelectorAll('.ownership-option').forEach(b=>b.addEventListener('click',()=>select(b.dataset.value)));otherInput.addEventListener('input',()=>{sessionStorage.setItem('healthtech-ownership-other',otherInput.value.trim());if(sessionStorage.getItem('healthtech-ownership')==='ownership-other')continueBtn.disabled=!otherInput.value.trim();});
 continueBtn.addEventListener('click',()=>{ownershipGateShown=true;page.remove();stateScreen.style.display='';});if(saved)select(saved);
}
function injectOwnershipPage(){
 const existing=document.querySelector('[data-ownership-question]');if(existing||ownershipGateShown||!isStatePage())return;
 const stateHeading=[...document.querySelectorAll('#root h1')].find(h=>h.textContent.trim()==='Which state are you operating in?');const stateScreen=stateHeading?.closest('.question-screen');if(!stateScreen)return;buildOwnershipPage(stateScreen);
}
new MutationObserver(()=>{if(!isStatePage())ownershipGateShown=false;injectOwnershipPage();}).observe(document.documentElement,{subtree:true,childList:true});injectOwnershipPage();