const labels={'company-owned':'Company-owned technology','founder-owned':'Founder-owned technology','university-owned':'University-controlled technology','licensed-in':'Technology licensed from a third party','jointly-owned':'Jointly owned technology','ownership-unclear':'Ownership needs clarification','ownership-other':'Other ownership arrangement','in-house':'Keep regulatory responsibility in-house','shared':'Share regulatory responsibility with a partner','partner-led':'Partner leads regulatory responsibility','undetermined':'Regulatory responsibility still to be decided'};
function textOf(el){return(el?.textContent||'').replace(/\s+/g,' ').trim()}
function sectionFor(title){const h=[...document.querySelectorAll('h1,h2,h3')].find(x=>textOf(x).toLowerCase().includes(title.toLowerCase()));return h?(h.closest('section')||h.parentElement):null}
function recommendations(title,max=3){const scope=sectionFor(title);if(!scope)return[];const cards=[...scope.querySelectorAll('article,.card,.option-card,.recommendation-card,.result-card')];let ranked=cards.filter(c=>/recommended|best fit|strong fit|primary|priority/i.test(textOf(c)));if(!ranked.length)ranked=cards;const out=[];for(const c of ranked){const h=c.querySelector('h2,h3,h4');const name=textOf(h);if(name&&!/why this result|decision tree/i.test(name)&&!out.includes(name))out.push(name);if(out.length>=max)break}return out}
function pills(items){return items.map((x,i)=>`<div class="recap-pick"><span>${i===0?'Primary':'Also consider'}</span><strong>${x}</strong></div>`).join('')}
function makeRecap(){if(document.querySelector('[data-personalized-recap]'))return;const summary=[...document.querySelectorAll('h1,h2')].find(h=>textOf(h).includes('You’ve mapped the key decisions'));if(!summary)return;const section=summary.closest('section');if(!section)return;
 const funding=recommendations('How should you fund and develop the program?',3),license=recommendations('What type of license should you consider?',3),terms=recommendations('Which contractual terms deserve your attention?',5);const ownership=sessionStorage.getItem('healthtech-ownership')||'',reg=sessionStorage.getItem('healthtech-regulatory-responsibility')||'';
 const recap=document.createElement('section');recap.dataset.personalizedRecap='true';recap.className='personalized-recap';recap.innerHTML=`<span class="eyebrow">Your personalized recap</span><h2>Your recommended path at a glance</h2><p class="recap-lead">Here is a simplified recap of the recommendations generated from your answers. It brings the major choices together so you can see what to explore first and what to discuss with potential partners, investors and counsel.</p>
 <div class="recap-cards">
 ${funding.length?`<article class="recap-card"><div class="recap-number">1</div><div><span class="recap-label">Financing & development</span><h3>How to fund and develop the program</h3>${pills(funding)}<p><strong>Why:</strong> These options reflect your financing size, development stage, resource needs, desired control and willingness to share development risk.</p><p class="recap-next"><strong>Next step:</strong> Start conversations with funding sources or strategic partners that match the primary pathway, while keeping the alternatives available if terms are unattractive.</p></div></article>`:''}
 ${license.length?`<article class="recap-card"><div class="recap-number">2</div><div><span class="recap-label">Licensing</span><h3>License structures to explore</h3>${pills(license)}<p><strong>Why:</strong> These structures reflect how much exclusivity a partner may need versus how much control, future use and partnering flexibility you may want to retain.</p><p class="recap-next"><strong>Next step:</strong> Define the product, field, indication, territory, exclusivity and sublicensing boundaries before negotiating economics.</p></div></article>`:''}
 ${terms.length?`<article class="recap-card"><div class="recap-number">3</div><div><span class="recap-label">Contract priorities</span><h3>Terms to prioritize in negotiations</h3>${pills(terms)}<p><strong>Why:</strong> These provisions address the legal and execution risks most likely to affect whether the transaction delivers the intended value.</p><p class="recap-next"><strong>Next step:</strong> Put these terms on the term-sheet and counsel checklist early rather than waiting until the definitive agreement.</p></div></article>`:''}
 ${reg?`<article class="recap-card"><div class="recap-number">4</div><div><span class="recap-label">Regulatory responsibility</span><h3>${labels[reg]||reg}</h3><p><strong>Why:</strong> This affects regulatory strategy, submissions, compliance costs, safety and quality responsibilities, data access and control.</p><p class="recap-next"><strong>Next step:</strong> Carry this allocation consistently through the development agreement, license, quality/safety agreements and termination provisions.</p></div></article>`:''}
 ${ownership?`<article class="recap-card"><div class="recap-number">5</div><div><span class="recap-label">Ownership foundation</span><h3>${labels[ownership]||ownership}</h3><p><strong>Why:</strong> Financing and licensing recommendations only work if the organization has authority to grant the relevant technology rights.</p><p class="recap-next"><strong>Next step:</strong> Confirm chain of title, assignments, existing licenses and any third-party consents before a transaction advances.</p></div></article>`:''}
 </div><div class="recap-bottom"><strong>In simple terms</strong><p>${funding[0]?`Explore <b>${funding[0]}</b> first for financing/development. `:''}${license[0]?`If licensing is part of the strategy, begin with <b>${license[0]}</b>. `:''}${terms.length?`Give particular attention to <b>${terms.slice(0,3).join(', ')}</b> in negotiations. `:''}Then make sure ownership and regulatory responsibilities support the deal you ultimately choose.</p></div>`;
 const grid=section.querySelector('.summary-grid');if(grid)grid.insertAdjacentElement('beforebegin',recap);else summary.insertAdjacentElement('afterend',recap)}
let t;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(makeRecap,100)}).observe(document.documentElement,{subtree:true,childList:true});makeRecap();